---
title: "R0 | Wprowadzenie: praca domowa"
author: "Szymon Talaga, Mikołaj Biesaga, ISS UW"
date: "`r Sys.Date()`"
output: html_notebook
---

<hr>

* Indeksowanie ramek danych
* Statystyki grupowe
* Tablicowanie (*lookup table*)
* summary
* Podzbiór ramki + zapis + wczytanie

## Praca domowa

Tematem pracy domowej jest indeksowanie ramek danych i wykorzystywanie tych operacji do obliczania zagregowanych metryk, np. statystyk grupowych. Będziemy używać zbioru danych `iris`.

### Indeksowanie

#### Zad. 1.

Zapisz ekwiwalent polecenia `head(iris)` za pomocą indeksowania ramki danych.

*Podpowiedź*

Składnia indeksowania: `ramka[<indeks na wiersze>, <indeks na kolumny>]`, np. `iris[c(10, 15), c(1, 3)]`.


<!-- CSS styling -->
<style>
    html {
        height: 100%;
        font-size: 62.5%;
    }
    body {
        height: 100%;
        font-size: 1.6em;
        font-family: "Trebuchet MS", "Lucida Grande", "Lucida Sans Unicode", "Lucida Sans", sans-serif;
    }
    h1, h2, h3 {
        text-align: center;
    }
    h4.author, h4.date {
        margin: 0.75em 0 0 0;
        text-align: center;
    }
    h2, h3, h4, h5, h6 {
        margin: 2em 0 1em 0;
    }
    div#header {
        margin: 1em 0 1em 0;
    }
    hr {
        margin: 2em 0 2em 0;
    }
    pre {
        margin-bottom: 2em;
    }
</style>

<hr>

<!-- End of styling -->